FORMAT: 1A
HOST: http://webgis.nature.cz/aopkrest/Vzchu/

# AOPK ČR - VZCHÚ

Rozhraní pro získávání informací o **Velkoplošných chráněných územích ČR (VZCHÚ)**.

## VZCHÚ - filtrování dle názvu [/filter/{pattern}?f={f}]

+ Parameters
    + pattern: Český (string, optional) - řetězec pro vyhledání
    + f (string, optional) - formát výstupu
        + Default: html
        + Members
            + json
            + html
            + xml

### Přehled dotazů [GET]

+ Response 200 (application/json)
    + Attributes
        + SeznamLokalit (LokalitaVZCHU)
        + SeznamLokalit (LokalitaVZCHU)
        + SeznamLokalit (LokalitaVZCHU)


## VZCHÚ - karta dle ID [/{kod}?f={f}]

+ Parameters
    + kod: 63 (number) - Kod VZCHÚ
    + f (string, optional) - formát výstupu
        + Default: html
        + Members
            + json
            + html
            + xml

            
### Přehled dotazů [GET]

+ Response 200 (application/json)
    + Attributes (LokalitaVZCHU)

        
## VZCHÚ - přehled změn [/updateinfo?f={f}]

+ Parameters
    + f (string, optional) - formát výstupu
        + Default: html
        + Members
            + json
            + html
            + xml

            
### Přehled dotazů [GET]

+ Response 200 (application/json)

    + Attributes
        + SeznamZmen (ZmenaVZCHU)
        + SeznamZmen (ZmenaVZCHU)


# Data structures


## LokalitaVZCHU
+ Kod: 63 (number) - kód lokality v ústředním seznamu ochrany přírody
+ Nazev: Český ráj (string) - název lokality
+ Kategorie: CHKO (enum [string]) - kategorie chráněného území
    + Members
    + CHKO - Chráněná krajinná oblast
+ IdAopkOop: 86 (number) - ID Regionálního pracoviště AOPK ČR !!!!Zkontrolovat!!!!

## ZmenaVZCHU
+ Kod: 63 (number) - kód lokality v ústředním seznamu ochrany přírody
+ IdAopkOop: 86 (number) - ID Regionálního pracoviště AOPK ČR !!!!Zkontrolovat!!!!
+ ZmenaT: `2019-01-09` (string) - datum poslední změny tabelárních dat lokality
+ ZmenaG: `2019-01-10` (string) - datum poslední změny zákresu lokality